public class QuestionData {
    //Questions
    //answers-a,c,b,a,c
    String q1 = "Who is known as father of Java Programming Language?\n"+"a)James Gosling\nb)M. P Java\nc)Charel Babbage\nd)Blais Pascal\n";
    String q2 = "In java control statements break, continue, return, try-catch-finally and assert belongs to?\n"+"a)Selection statements\nb)Loop statements\nc)Transfer statements\nd)Pause Statement\n";
    String q3 = "Which provides runtime environment for java byte code to be executed?\n"+"a)JRE\nb)JVM\nc)JDK\nd)JAVAC\n";
    String q4 = "What is byte code in Java?\n"+"a)Code generated by a Java compiler\nb)Code generated by a Java Virtual Machine\nc)Name of Java source code file\nd)Block of code written inside a class\n";
    String q5 = "Which of the following are not Java keywords ?\n"+"a)double\nb)switch\nc)then\nd)instaceof\n";

    //answers-a,c,b,b,d
    String q6 = "Which of these have highest precedence?\n"+"a) ()\nb) ++\nc)*\nd)>>\n";
    String q7 = "Java language was initially called as ________?\n"+"a)Sumatra\nb)J++\nc)Oak\nd)Pine\n";
    String q8 = "Which one is a template for creating different objects ?\n"+"a)An Array\nb)A Class\nc)Interface\nd)Method\n";
    String q9 = "Which symbol is used to contain the values of automatically initialized arrays?\n"+"a)Brackets\nb)Braces\nc)Parentheses\nd)Comma\n";
    String q10 = "Which of these operators is used to allocate memory to array variable in Java?\n"+"a)alloc\nb)malloc\nc)new malloc\nd)new\n";

    //answers-b,c,a,d,c
    String q11 = "Which statement transfer execution to different parts of your code based on the value of an expression?\n"+"a)If\nb)Switch\nc)Nested-if\nd)if-else-if\n";
    String q12 = "Modulus operator (%) can be applied to which of these?\n"+"a)Integers\nb)Floating - point numbers\nc)Both a and b\nd)None of These\n";
    String q13 = "What feature of OOP has a super-class sub-class concept?\n"+"a)Hierarchical inheritance\nb)Single inheritance\nc)Multiple inheritances\nd)Multilevel inheritance\n";
    String q14 = "What is the full form of JVM ?\n"+"a)Java Very Large Machine\nb)Java Verified Machine\nc)Java Very Small Machine\nd)Java Virtual Machine\n";
    String q15 = "Which of the following are not Java modifiers?\n"+"a)public\nb)private\nc)friendly\nd)transient\n";

    //answers- a,c,b,a,b
    String q16 = "In Java code, the line that begins with /* and ends with */ is known as?\n"+"a)Multiline comment\nb)Single line comment\nc)Both a & b\nd)None of these\n";
    String q17 = "Division operator has ____ precedence over multiplication operator.\n"+"a)Highest\nb)Least\nc)Equal\nd)None of these\n";
    String q18 = "What is the name of the method used to start a thread execution?\n"+"a)init();\nb)start();\nc)run();\nd)resume();\n";
    String q19 = "Which of the following will directly stop the execution of a Thread?\n"+"a)wait()\nb)notify()\nc)notifyall()\nd)exits synchronized code\n";
    String q20 = "Which method must be defined by a class implementing the java.lang.Runnable interface?\n"+"a)void run()\nb)public void run()\nc)public void start()\nd)void run(int priority)\n";

    //String  = "?\n"+"a)\n b)\nc)\n d)\n";
}
